test: #6 add test, is currently failing
TypeError: Cannot read property 'type' of undefined
    at ./x-tree-diff-plus/src/XTreeDiffPlus.ts:242:80

Since cA may contain more nodes than cB.